'use strict';
module.exports = {
  nav: { shop: 'Shop', all: 'All products', offers: 'On sale', new: 'New', updates: 'Updates', membership: 'Membership', blog: 'Blog', about: 'About us', contact: 'Contact', favorites: 'Favorites', cart: 'Cart', account: 'My account', downloads: 'My downloads', admin: 'Admin panel', login: 'Sign in', register: 'Create account', logout: 'Sign out', search: 'Search systems, templates…', theme: 'Toggle light / dark mode', home: 'Home', enter: 'Sign in', bundles: 'Bundles', compare: 'Compare' },
  home: { explore: 'Browse the shop', plans: 'See memberships', featured: 'Featured products', featuredEyebrow: 'Selection', seeAll: 'See the whole shop →', categories: 'Categories', explore2: 'Explore', newest: 'New releases', newestEyebrow: 'Just published', seeNew: 'See all →', why: 'Why', whyEyebrow: 'Why choose us', testimonials: 'What customers say', updates: 'Latest updates', history: 'See history →', custom: 'Need something custom?', customText: 'We adapt any of our systems to your business or build one from scratch.', whatsapp: 'Message on WhatsApp', form: 'Contact form', stats: { products: 'systems, templates and scripts', updates: 'updates published', sales: 'sales completed', response: 'maximum response time' }, proof: 'registered customers', sales: 'sales', support: 'support in under 24 h', bundles: 'Discounted bundles', bundlesEyebrow: 'Save by buying together', posts: 'From the blog', postsEyebrow: 'Guides and tutorials' },
  card: { demo: 'Demo', details: 'Details', buy: 'Buy', noReviews: 'No reviews', new: 'New' },
  product: { buy: 'Buy now', addCart: 'Add to cart', demo: 'Live demo', whatsapp: 'Ask on WhatsApp', download: 'Download', license: 'License', updates: 'Updates', updatesVal: 'Included for life', delivery: 'Delivery', deliveryVal: 'Instant download (.zip)', membership: 'Membership', membershipVal: 'Included in every plan', sales: 'Sales', favorites: 'Favorites', description: 'Description', features: 'Features', changelog: 'Version history', reviews: 'Customer reviews', requirements: 'Requirements / Stack', related: 'Related products', firstReview: 'Be the first to review', faq: 'Frequently asked questions', package: "What's inside the ZIP", video: 'Demo video', compare: 'Compare', bundle: 'Save with the bundle', included: 'Included in your membership.', bought: 'You already own this product.' },
  shop: { title: 'Shop', results: 'results', filters: 'Filters', clear: 'Clear', show: 'Show', price: 'Price (USD)', onlyOffers: 'On sale only', category: 'Category', all: 'All', tech: 'Technology', rating: 'Rating', orMore: 'or more', any: 'Any', apply: 'Apply filters', everything: 'Everything', offers: '🔥 Deals', sort: { recent: 'Newest', popular: 'Best sellers', rating: 'Top rated', price_asc: 'Price: low to high', price_desc: 'Price: high to low', name: 'Name A–Z' }, empty: 'No products found', emptyText: 'Try another search, remove a filter or browse all categories.', seeAll: 'See the whole shop' },
  cart: { title: 'Cart', product: 'product', products: 'products', remove: 'Remove', empty: 'Empty cart', continue: 'Keep shopping', summary: 'Summary', total: 'Total', pay: 'Checkout', emptyTitle: 'Your cart is empty', explore: 'Browse the shop' },
  checkout: { title: 'Checkout', step: 'Last step', summary: 'Summary', total: 'Total', coupon: 'Have a coupon?', apply: 'Apply', remove: 'Remove', choose: 'Choose how to pay' },
  account: { title: 'My account', hello: 'Hi', purchases: 'Purchases', downloads: 'Downloads', membership: 'Membership', licenses: 'Licenses', tickets: 'Support', profile: 'Profile', activate: 'Get a membership' },
  auth: { login: 'Sign in', register: 'Create account', email: 'Email', password: 'Password', enter: 'Sign in', forgot: 'Forgot your password?', noAccount: "Don't have an account?", haveAccount: 'Already have an account?' },
  footer: { shop: 'Shop', help: 'Help', payments: 'Payment methods', terms: 'Terms and licenses', rights: 'Licensed code, real support.' },
  common: { language: 'Language', spanish: 'Spanish', english: 'English' },
};
