'use strict';
module.exports = {
  nav: { shop: 'Tienda', all: 'Todos los productos', offers: 'En oferta', new: 'Nuevos', updates: 'Actualizaciones', membership: 'Membresía', blog: 'Blog', about: 'Nosotros', contact: 'Contacto', favorites: 'Favoritos', cart: 'Carrito', account: 'Mi cuenta', downloads: 'Mis descargas', admin: 'Panel de administración', login: 'Ingresar', register: 'Crear cuenta', logout: 'Cerrar sesión', search: 'Buscar sistemas, plantillas…', theme: 'Cambiar entre modo claro y oscuro', home: 'Inicio', enter: 'Entrar', bundles: 'Paquetes', compare: 'Comparar' },
  home: { explore: 'Explorar la tienda', plans: 'Ver membresías', featured: 'Productos destacados', featuredEyebrow: 'Selección', seeAll: 'Ver toda la tienda →', categories: 'Categorías', explore2: 'Explora', newest: 'Nuevos lanzamientos', newestEyebrow: 'Recién publicados', seeNew: 'Ver todos →', why: '¿Por qué', whyEyebrow: 'Por qué elegirnos', testimonials: 'Lo que dicen los clientes', updates: 'Últimas actualizaciones', history: 'Ver historial →', custom: '¿Necesitas algo a medida?', customText: 'Adaptamos cualquiera de nuestros sistemas a tu negocio o desarrollamos uno desde cero.', whatsapp: 'Escribir por WhatsApp', form: 'Formulario de contacto', stats: { products: 'sistemas, plantillas y scripts', updates: 'actualizaciones publicadas', sales: 'ventas realizadas', response: 'tiempo máximo de respuesta' }, proof: 'clientes registrados', sales: 'ventas', support: 'soporte en menos de 24 h', bundles: 'Paquetes con descuento', bundlesEyebrow: 'Ahorra comprando junto', posts: 'Del blog', postsEyebrow: 'Guías y tutoriales' },
  card: { demo: 'Demo', details: 'Detalles', buy: 'Comprar', noReviews: 'Sin reseñas', new: 'Nuevo' },
  product: { buy: 'Comprar ahora', addCart: 'Añadir al carrito', demo: 'Ver demo en vivo', whatsapp: 'Consultar por WhatsApp', download: 'Descargar', license: 'Licencia', updates: 'Actualizaciones', updatesVal: 'Incluidas de por vida', delivery: 'Entrega', deliveryVal: 'Descarga inmediata (.zip)', membership: 'Membresía', membershipVal: 'Incluido en todos los planes', sales: 'Ventas', favorites: 'Favoritos', description: 'Descripción', features: 'Características', changelog: 'Historial de versiones', reviews: 'Reseñas de clientes', requirements: 'Requisitos / Stack', related: 'Productos relacionados', firstReview: 'Sé el primero en opinar', faq: 'Preguntas frecuentes', package: 'Qué incluye el ZIP', video: 'Vídeo de demostración', compare: 'Comparar', bundle: 'Ahorra con el paquete', included: 'Incluido en tu membresía.', bought: 'Ya compraste este producto.' },
  shop: { title: 'Tienda', results: 'resultados', filters: 'Filtros', clear: 'Limpiar', show: 'Mostrar', price: 'Precio (USD)', onlyOffers: 'Solo en oferta', category: 'Categoría', all: 'Todas', tech: 'Tecnología', rating: 'Valoración', orMore: 'o más', any: 'Cualquiera', apply: 'Aplicar filtros', everything: 'Todo', offers: '🔥 Ofertas', sort: { recent: 'Más recientes', popular: 'Más vendidos', rating: 'Mejor valorados', price_asc: 'Precio: menor a mayor', price_desc: 'Precio: mayor a menor', name: 'Nombre A–Z' }, empty: 'No encontramos productos', emptyText: 'Prueba con otra búsqueda, quita algún filtro o explora todas las categorías.', seeAll: 'Ver toda la tienda' },
  cart: { title: 'Carrito', product: 'producto', products: 'productos', remove: 'Quitar', empty: 'Vaciar carrito', continue: 'Seguir comprando', summary: 'Resumen', total: 'Total', pay: 'Ir a pagar', emptyTitle: 'Tu carrito está vacío', explore: 'Explorar la tienda' },
  checkout: { title: 'Finalizar compra', step: 'Último paso', summary: 'Resumen', total: 'Total', coupon: '¿Tienes un cupón?', apply: 'Aplicar', remove: 'Quitar', choose: 'Elige cómo pagar' },
  account: { title: 'Mi cuenta', hello: 'Hola', purchases: 'Compras', downloads: 'Descargas', membership: 'Membresía', licenses: 'Licencias', tickets: 'Soporte', profile: 'Perfil', activate: 'Activar membresía' },
  auth: { login: 'Iniciar sesión', register: 'Crear cuenta', email: 'Correo', password: 'Contraseña', enter: 'Entrar', forgot: '¿Olvidaste tu contraseña?', noAccount: '¿Aún no tienes cuenta?', haveAccount: '¿Ya tienes cuenta?' },
  footer: { shop: 'Tienda', help: 'Ayuda', payments: 'Métodos de pago', terms: 'Términos y licencias', rights: 'Código con licencia, soporte real.' },
  common: { language: 'Idioma', spanish: 'Español', english: 'Inglés' },
};
